# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68cdaa6b724fef90c6542c1d97a34d827861eea42cb36a14bb21343d2f86584a60166b23ef93b80a04c14124711e5910ced25af0cb9cf281beb0262e240f87ec

test:
  secret_key_base: 4a4f810bd3a1b98bd44086e4a93276110fb1b564f72087d3116149258110b1be906782bfda25d4a6888c95b15340164f8afa5307931c1f2683b2cb2da59d11dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
